
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 29 15:31:56 GMT-06:00 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DIVIDE = 11;
  public static final int NUMBER = 12;
  public static final int MOD = 10;
  public static final int SEMI = 4;
  public static final int EQUAL = 3;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int TIMES = 7;
  public static final int LPAREN = 8;
}

